= Quartz Examples

This project provides examples of https://github.com/quartz-scheduler/quartz[Quartz Scheduler] that
demonstrate some of its features.

The Quartz Scheduler is a very flexible scheduling library. The easiest way to learn is to explore some
the examples provided here, and then try something on your own. There are many configuration settings
you can use to control the scheduler, and you can easily test any of these in a Java properties file
to explore the features.

This project configured Quartz library with https://logback.qos.ch[Logback] as the logger, and default
to INFO level to STDOUT for log messages. You may edit the `src/main/resources/logback.xml` to increase
the level to "DEBUG" if you wish to see more activities in action by the scheduler.

The project also provided a default PostgreSQL database as backend storage. If you wish to test
out the scheduler in any other DB, just create similar configuration and change out the datasource
configuration settings. You will find many quartz configuration examples under
`src/main/resources/zemian/quartz/examples` folder.


= Requirements

- Java 7 or higher
- Maven 3.3 or higher
- Postgres 9 or higher

= Setup Postgres Database

For convenience, there is a copy of schema script under `db/tables_postgres.sql`. For latest copy
of this file, you should get it from the quartz project site.

To prepare Postgres DB for quartz using default 'postgres' user, try the following:

----
postgres# create database quartz;
postgres# \c quartz
postgres# \i /path/to/quartz-zemian-examples/db/tables_postgres.sql
----


= Quartz Examples

This project provide a reusable QuartzServer program that can take any quartz properties configuration
file and run it as a server. You can press `CTRL+C` keys on console to stop it.

== RAM Scheduler

To run a quartz scheduler as a server using in memory storage, type the following:

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzServer -DquartzConfig=zemian/quartz/examples/quartz.properties
----

== Postgres DB Scheduler

To run a quartz scheduler as a server connecting to postgres DB, type the following:

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzServer -DquartzConfig=zemian/quartz/examples/quartz-postgres.properties
----

== Inserting Jobs Programmatically Using API

There are many ways to insert jobs into scheduler. One way is programmatically using the API. Quartz
uses the same `org.quartz.Scheduler` interface as the server for inserting job. You just need to ensure
NOT to start the scheduler instance since you are writing only a "client" program. Simply use the API to
insert/update jobs and then exit.

Here is an example of a client program that insert couple running jobs. Note that you can use the same
configuration file you pass to "server" side so you connect to the same datasource store.

You should create a new client program for each set of new jobs that you want to create and insert.

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzClient -DquartzConfig=zemian/quartz/examples/quartz-postgres.properties
----
