= Quartz Examples

This project provide examples of Quartz Scheduler that demonstrate some of its features.

The Quartz Scheduler is a very flexible scheduling library, however it requires one to understand how it 
work before you can effectively use it. The easiest way to learn is to explore these examles and then
try something on your own. There are many configuration settings you can use to control the scheduler,
and you can easily test any of these in a Java properties file to explore the features.

See http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration for configuration
details.


= Examples

== RAM Scheduler

To run a quartz scheduler as a server using in memory, type the following:

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzServer -DquartzConfig=zemian/quartz/examples/quartz.properties
----

== Postgres DB Scheduler

To run a quartz scheduler as a server connecting to postgre DB, type the following:

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzServer -DquartzConfig=zemian/quartz/examples/quartz-postgres.properties
----

== Inserting Jobs

There are many ways to insert jobs into scheduler. One way is programmatically using the API.

NOTE: You should NOT start the scheduler if you simply want to use API to insert jobs!

Here is an example of a client program that insert couple running jobs. You can change the quartz properties file
to any of datastore you wish to insert the job into.

----
mvn exec:java -Dexec.mainClass=zemian.quartz.examples.QuartzClient -DquartzConfig=zemian/quartz/examples/quartz-postgres.properties
----
